# Generated by hand for exam models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0140_alter_contest_format_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("prompt", models.TextField(blank=True, verbose_name="prompt")),
                (
                    "correct_choice",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                        verbose_name="correct choice",
                    ),
                ),
                (
                    "contest_problem",
                    models.OneToOneField(
                        on_delete=models.deletion.CASCADE,
                        related_name="exam_question",
                        to="judge.contestproblem",
                        verbose_name="contest problem",
                    ),
                ),
            ],
            options={
                "verbose_name": "exam question",
                "verbose_name_plural": "exam questions",
            },
        ),
        migrations.CreateModel(
            name="ExamChoice",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "label",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                        verbose_name="label",
                    ),
                ),
                ("text", models.TextField(verbose_name="choice text")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="choices",
                        to="judge.examquestion",
                        verbose_name="question",
                    ),
                ),
            ],
            options={
                "verbose_name": "exam choice",
                "verbose_name_plural": "exam choices",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="ExamResponse",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("selected_choice", models.CharField(choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")], max_length=1, verbose_name="selected choice")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "participation",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="exam_responses",
                        to="judge.contestparticipation",
                        verbose_name="participation",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="responses",
                        to="judge.examquestion",
                        verbose_name="question",
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.CASCADE,
                        related_name="exam_response",
                        to="judge.submission",
                        verbose_name="submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "exam response",
                "verbose_name_plural": "exam responses",
            },
        ),
        migrations.AlterUniqueTogether(
            name="examchoice",
            unique_together={("question", "label")},
        ),
        migrations.AlterUniqueTogether(
            name="examresponse",
            unique_together={("question", "participation")},
        ),
    ]
