# Generated by Django 3.2.25 on 2025-09-22 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0142_auto_20250922_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestparticipation',
            name='assigned_exam_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_participations', to='judge.exampaper', verbose_name='assigned exam paper'),
        ),
        migrations.AddField(
            model_name='contestparticipation',
            name='exam_finalized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='exam submitted at'),
        ),
        migrations.AddField(
            model_name='contestparticipation',
            name='exam_locked',
            field=models.BooleanField(default=False, help_text='Whether the participant has been locked out of the exam.', verbose_name='exam locked'),
        ),
        migrations.AddField(
            model_name='contestparticipation',
            name='exam_locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='exam locked at'),
        ),
        migrations.AddField(
            model_name='contestparticipation',
            name='exam_violation_count',
            field=models.PositiveIntegerField(default=0, verbose_name='exam violation count'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='code',
            field=models.CharField(default='A', max_length=16, verbose_name='exam code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exampaper',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_papers', to='judge.contest', verbose_name='contest'),
        ),
        migrations.AlterUniqueTogether(
            name='exampaper',
            unique_together={('contest', 'code')},
        ),
    ]
